close #1 - Added support for MariaDB

diff --git a/src/backup b/src/backup
--- a/src/backup
+++ b/src/backup
@@ -9,10 +9,10 @@ cleanup() {
   find /backups/ -type f -not -name ".*" -mtime +$CLEANUP_OLDER_THAN -exec rm {} \;
 }
 
-if [ -z "$MYSQL_ENV_MYSQL_HOST" ]; then echo "Error: MYSQL_ENV_MYSQL_HOST not set"; echo "Finished: FAILURE"; exit 1; fi
-if [ -z "$MYSQL_ENV_MYSQL_USER" ]; then echo "Error: MYSQL_ENV_MYSQL_USER not set"; echo "Finished: FAILURE"; exit 1; fi
-if [ -z "$MYSQL_ENV_MYSQL_DATABASE" ]; then echo "Error: MYSQL_ENV_MYSQL_DATABASE not set"; echo "Finished: FAILURE"; exit 1; fi
-if [ -z "$MYSQL_ENV_MYSQL_PASSWORD" ]; then echo "Error: MYSQL_ENV_MYSQL_PASSWORD not set"; echo "Finished: FAILURE"; exit 1; fi
+if [ -z "$DATABASE_HOST" ]; then echo "Error: DATABASE_HOST not set"; echo "Finished: FAILURE"; exit 1; fi
+if [ -z "$DATABASE_USER" ]; then echo "Error: DATABASE_USER not set"; echo "Finished: FAILURE"; exit 1; fi
+if [ -z "$DATABASE_NAME" ]; then echo "Error: DATABASE_NAME not set"; echo "Finished: FAILURE"; exit 1; fi
+if [ -z "$DATABASE_PASSWORD" ]; then echo "Error: DATABASE_PASSWORD not set"; echo "Finished: FAILURE"; exit 1; fi
 
 if [ -n "$CLEANUP_OLDER_THAN" ]; then cleanup;  fi
 
@@ -20,6 +20,10 @@ echo 'creating backup archive of /var/www/html'
 tar --create --gzip -vv --directory="/var/www/html/" --file="/backups/backup_`date '+%Y%m%d'`.tar.gz" "./"
 
 echo 'creating database dump'
-mysqldump --host="${MYSQL_ENV_MYSQL_HOST}" --add-drop-table --no-tablespaces --user="${MYSQL_ENV_MYSQL_USER}" --password="${MYSQL_ENV_MYSQL_PASSWORD}" "${MYSQL_ENV_MYSQL_DATABASE}" --single-transaction --column-statistics=0 | bzip2 -c > "/backups/backup_`date '+%Y%m%d'`.sql.bz2"
+if [ "$DATABASE_CLIENT" == "mariadb" ]; then
+  mariadb-dump --host="${DATABASE_HOST}" --add-drop-table --no-tablespaces --user="${DATABASE_USER}" --password="${DATABASE_PASSWORD}" "${DATABASE_NAME}" --single-transaction | bzip2 -c > "/backups/backup_`date '+%Y%m%d'`.sql.bz2"
+else
+  mysqldump --host="${DATABASE_HOST}" --add-drop-table --no-tablespaces --user="${DATABASE_USER}" --password="${DATABASE_PASSWORD}" "${DATABASE_NAME}" --single-transaction --column-statistics=0 | bzip2 -c > "/backups/backup_`date '+%Y%m%d'`.sql.bz2"
+fi
 
 echo 'Finished: SUCCESS'
diff --git a/src/restore b/src/restore
--- a/src/restore
+++ b/src/restore
@@ -9,11 +9,11 @@ then
     exit 1
 fi
 
-if [ -z "$MYSQL_ENV_MYSQL_HOST" ]; then echo "Error: MYSQL_ENV_MYSQL_HOST not set"; echo "Finished: FAILURE"; exit 1; fi
-if [ -z "$MYSQL_ENV_MYSQL_USER" ]; then echo "Error: MYSQL_ENV_MYSQL_USER not set"; echo "Finished: FAILURE"; exit 1; fi
-if [ -z "$MYSQL_ENV_MYSQL_DATABASE" ]; then echo "Error: MYSQL_ENV_MYSQL_DATABASE not set"; echo "Finished: FAILURE"; exit 1; fi
-if [ -z "$MYSQL_ENV_MYSQL_PASSWORD" ]; then echo "Error: MYSQL_ENV_MYSQL_PASSWORD not set"; echo "Finished: FAILURE"; exit 1; fi
-if [ -z "$MYSQL_PORT_3306_TCP_PORT" ]; then echo "Error: MYSQL_PORT_3306_TCP_PORT not set"; echo "Finished: FAILURE"; exit 1; fi
+if [ -z "$DATABASE_HOST" ]; then echo "Error: DATABASE_HOST not set"; echo "Finished: FAILURE"; exit 1; fi
+if [ -z "$DATABASE_USER" ]; then echo "Error: DATABASE_USER not set"; echo "Finished: FAILURE"; exit 1; fi
+if [ -z "$DATABASE_NAME" ]; then echo "Error: DATABASE_NAME not set"; echo "Finished: FAILURE"; exit 1; fi
+if [ -z "$DATABASE_PASSWORD" ]; then echo "Error: DATABASE_PASSWORD not set"; echo "Finished: FAILURE"; exit 1; fi
+if [ -z "$DATABASE_PORT" ]; then echo "Error: DATABASE_PORT not set"; echo "Finished: FAILURE"; exit 1; fi
 
 if ! [[ $1 =~ ^[a-zA-Z0-9_-]+$ ]]
 then
@@ -49,16 +49,20 @@ echo "restoring files from $FILES_ARCHIVE to /var/www/html"
 tar -xzf "${FILES_ARCHIVE}" --directory="/var/www/html/"
 
 # update wp-config.php
-sed -i s/"define('DB_NAME', '.*');"/"define('DB_NAME', '$MYSQL_ENV_MYSQL_DATABASE');"/g /var/www/html/wp-config.php
-sed -i s/"define('DB_USER', '.*');"/"define('DB_USER', '$MYSQL_ENV_MYSQL_USER');"/g /var/www/html/wp-config.php
-sed -i s/"define('DB_PASSWORD', '.*');"/"define('DB_PASSWORD', '$MYSQL_ENV_MYSQL_PASSWORD');"/g /var/www/html/wp-config.php
-sed -i s/"define('DB_HOST', '.*');"/"define('DB_HOST', '$MYSQL_ENV_MYSQL_HOST:$MYSQL_PORT_3306_TCP_PORT');"/g /var/www/html/wp-config.php
+sed -i s/"define('DB_NAME', '.*');"/"define('DB_NAME', '$DATABASE_NAME');"/g /var/www/html/wp-config.php
+sed -i s/"define('DB_USER', '.*');"/"define('DB_USER', '$DATABASE_USER');"/g /var/www/html/wp-config.php
+sed -i s/"define('DB_PASSWORD', '.*');"/"define('DB_PASSWORD', '$DATABASE_PASSWORD');"/g /var/www/html/wp-config.php
+sed -i s/"define('DB_HOST', '.*');"/"define('DB_HOST', '$DATABASE_HOST:$DATABASE_PORT');"/g /var/www/html/wp-config.php
 
 # set correct file owner
 chown -R www-data:www-data /var/www/html
 
 # restore database
 echo "restoring data from mysql dump file $SQL_ARCHIVE"
-bunzip2 < "${SQL_ARCHIVE}" | mysql --user="${MYSQL_ENV_MYSQL_USER}" --password="${MYSQL_ENV_MYSQL_PASSWORD}" --host="${MYSQL_ENV_MYSQL_HOST}" "${MYSQL_ENV_MYSQL_DATABASE}"
+if [ "$DATABASE_CLIENT" == "mariadb" ]; then
+  bunzip2 < "${SQL_ARCHIVE}" | mariadb --user="${DATABASE_USER}" --password="${DATABASE_PASSWORD}" --host="${DATABASE_HOST}" "${DATABASE_NAME}"
+else
+  bunzip2 < "${SQL_ARCHIVE}" | mysql --user="${DATABASE_USER}" --password="${DATABASE_PASSWORD}" --host="${DATABASE_HOST}" "${DATABASE_NAME}"
+fi
 
 echo 'Finished: SUCCESS'
